### ISSUE TITLE
Absent vscode-jsonrpc dependency

### ISSUE THREAD

**Issue by martinjlowm** [typescript-language-server/typescript-language-server#144]
I understand the project is looking for new maintainer(s), but I'll report this issue anyway.

`lsp-protocol.calls.proposed.js` is output with a dependency on `vscode-jsonrpc` at https://github.com/theia-ide/typescript-language-server/blob/master/server/src/lsp-protocol.calls.proposed.ts#L43. Yet, this dependency is not listed in the `package.json`.

I'm not sure if it was the intention to only emit types for the declaration files.

**Comment by rchl** [comment]
There is no direct dependency on it but it is included in the project indirectly through `vscode-languageserver` -> `vscode-languageserver-protocol` -> `vscode-jsonrpc`.

What problem is it causing exactly?

**Comment by rchl** [comment]
Will close this since I don't think there is any actual problem with how it is now.

I suppose one could argue that it's a good practice to define the explicitly used dependencies but in this case `scode-languageserver-protocol` pins `vscode-jsonrpc` to specific version so I'm worried that we could end up with two different versions in the project if I add it explicitly.
