### ISSUE TITLE
Bump project dependencies to latest stable versions

### ISSUE THREAD

**Issue by DonnieWest** [typescript-language-server/typescript-language-server#158]
Currently, we're major versions behind on several dependencies. Notably, some core ones like `typescript` and our LSP lib. Some of these may be breaking changes, so we need to upgrade and resolve all breaking changes

**Comment by rchl** [comment]
We are mostly up to date now. At least with the important stuff like typescript and libraries.

Some small utilities made by sindresorhus are problematic because sindre decided to make all of his stuff mjs-only and that creates all sort of problems with testing and minimum requirements. So we're not gonna update those for now at least.
