### ISSUE TITLE
Ability to send `$/progress` messages

### ISSUE THREAD

**Issue by w0ng** [typescript-language-server/typescript-language-server#237]
When working on large repos, it can take ~1min for typescript server from `textDocument/didOpen` ->  `textDocument/publishDiagnostics`.

Is it possible to add the ability to send send `$/progress` messages if the client attaches a progress token to the request so that users are able to convert this to some type of "loading" indicator e.g. in vim's status bar?

https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#initiatingWorkDoneProgress

**Comment by rchl** [comment]
Sounds good but I'm not sure if we have any way to tell the progress at the `typescript-language-server` <-> `ts_server` level when requesting diagnostics. We likely won't be able to tell if it's gonna take 2 or 20 seconds to get the results.

**Comment by rchl** [comment]
Thinking about it more, I don't see this being doable because the `textDocument/didOpen` response is not waiting for the diagnostics to be reported. Diagnostics are requested from the server side and posted to the client as a notification so it's not possible to attach progress to that.

Unless in your case the `textDocument/didOpen` actually takes one minute before it returns a response?

**Comment by rchl** [comment]
Added server-initiated progress in #326 since I've found out that we are getting appropriate events from Typescript.
