### ISSUE TITLE
Add ability to pass `--disableAutomaticTypingAcquisition` flag to the tsserver executable

### ISSUE THREAD

**Issue by dmitmel** [typescript-language-server/typescript-language-server#238]
What the title says, essentially. Ideally an option should be added for just passing custom command-line arguments to tsserver. The code that needs changing is <https://github.com/theia-ide/typescript-language-server/blob/9ce7aa4ae399a5b66ea0bc027447a14aed273e3a/server/src/tsp-client.ts#L89-L109>, I can open a PR.

**Comment by rchl** [comment]
Sounds good to me to expose the option but the preferred way is to do it through `initializationOptions` rather than command line options. It's more flexible that way. Currently those are supported options: https://github.com/theia-ide/typescript-language-server/blob/ed098d340a87fa5fd27365a568b54823b5e92a91/server/src/ts-protocol.ts#L24-L27

**Comment by dmitmel** [comment]
Yes, of course. Isn't this how all other options in the chunk I linked are passed already?
