### ISSUE TITLE
Use yarn instead of npm as package manager

### ISSUE THREAD

**Issue by ambasta** [typescript-language-server/typescript-language-server#343]
Currently tsserver expects npm at `npmLocation` When yarnpkg is being used, npm should be optional and tsserver should rely on yarn for Automatic Type Acquisition.

Currently, invoking tsserver on a system w/o npm but using yarn throws

```
/bin/sh: line 1: /usr/bin/npm: No such file or directory
```

Instead of npmLocation, tsserver should accept a `packageManager: yarn|npm` and `packageManagerLocation: <path>` instead

**Comment by rchl** [comment]
This server can't do anything about it because the code that handles that is in the `typescript` package - https://github.com/microsoft/TypeScript/blob/d4170586f04a1d6430024a05ddc7bb2bf5a5c5b8/src/typingsInstaller/nodeTypingsInstaller.ts#L109-L117

So this would be something for the https://github.com/microsoft/TypeScript/issues instead.
