### ISSUE TITLE
Would you be interested in code actions?

### ISSUE THREAD

**Issue by olrtg** [typescript-language-server/typescript-language-server#616]
Hello! I been wanted to create a neovim plugin that ports [this vscode extension](https://github.com/xsburg/vscode-javascript-booster/) code actions to improve my react/typescript workflow but there's not a way to do that without creating my own language server.

**This is the list of code actions:**
-   Conditions

    -   Flip if-else
    -   Remove redundant else
    -   Replace if-else with ?:
    -   Simplify if-else
    -   Flip ?:
    -   Simplify ?:
    -   Merge nested `if` statements **(new)**

-   Declarations

    -   Convert var/const to let
    -   Convert var to const
    -   Split into multiple declarations
    -   Split into declaration and initialisation
    -   Merge declaration and initialisation

-   Strings

    -   Replace string with template string
    -   Replace template string with regular string
    -   Split string under cursor
    -   Trim whitespaces inside string **(new)**

-   Functions

    -   Convert shorthand arrow function to statement
    -   Convert to shorthand arrow function
    -   Add parens to single arrow function parameter
    -   Convert function to arrow function
    -   Convert arrow function to regular function **(new)**
    -   Convert function declaration to arrow function **(new)**

-   Async

    -   \[on selection\] Run selected await statements in parallel with `Promise.all`

-   TypeScript

    -   Convert enum to string-enum **(new)**
    -   Convert string-enum to type union **(new)**
    -   Convert type union of strings to string-enum **(new)**

-   JSX / TSX

    -   Wrap value with {} (JSX attributes)
    -   Remove {} from JSX attribute
    -   Collapse/Expand empty tag

-   React

    -   Wrap function into useCallback() hook **(new)**
    -   React: Wrap component function with React.forwardRef() **(new)**
    -   React: Wrap component function with React.memo() **(new)**
    -   React: Convert function to React.FunctionComponent<Props> declaration **(new)**

I've created this issue to know if this is something that you would accept a PR for. I don't know if all of the above will be submitted but just to make a decision on what to do.

 Thanks in advance 🤘🏽

**Comment by rchl** [comment]
Sorry but I don't think it's a good idea for multiple reasons:
 - it likely would add a significant performance overheard as it would be parsing code separately from Typescript. Its readme says:
    > The extension uses [Babylon](https://github.com/babel/babel/tree/master/packages/babylon) to parse the code and then manipulates the abstract syntax tree using [jscodeshift](https://github.com/facebook/jscodeshift).
 - it would add significant amount of code that would have to be maintained and there isn't really enough resources available to do that.
 - There is no good reason for it to be bundled with this server since it doesn't share any code nor it utilizes typescript in any way.

But on the bright side, that extension already implements LSP server at https://github.com/xsburg/vscode-javascript-booster/tree/master/server. The client (extension) part seems pretty slim so while it might require a bit of glue code on the client to implement some [custom commands](https://github.com/xsburg/vscode-javascript-booster/blob/be4237653a9be97dc012bcba8c4f500d38760eaf/client/src/extension.ts#L18-L21), it shouldn't be too much work. I haven't investigated if those custom commands are a necessity.

**Comment by rchl** [comment]
And also seeing issues like those:

- https://github.com/xsburg/vscode-javascript-booster/issues/40
- https://github.com/xsburg/vscode-javascript-booster/issues/32
- https://github.com/xsburg/vscode-javascript-booster/issues/15

both confirm my suspicions about performance overhead and make me think that the package is not actively maintained since those issues got no response from the author.

**Comment by olrtg** [comment]
Hey @rchl ! After your response did some more research and I've found a plugin called [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) which allows me to inject code actions in neovim. Thank you so much anyway! I thought that would be your answer since we have these type of plugins for vscode (which also uses the LSP and they're not bundled with the language server)
