### ISSUE TITLE
Create path if not existent when calling applyRenameFile

### ISSUE THREAD

**Issue by thraizz** [typescript-language-server/typescript-language-server#625]
Hi, would it be possible to make `applyRenameFile` create a target path, if it is not existing? Currently, it errors out with `ENOENT: No such file or directory.` when trying to rename a file's path.

Of course, we could implement this in clients as well.

Thanks for the great LSP!

**Comment by rchl** [comment]
LSP spec supports (since version 3.13) file renames so this code could be converted to a spec compliant variant which would mean that your client might support that already and if not, at least the functionality wouldn't be specific to this server.

That's IMO the best option as I wouldn't want the server to do file operations itself because server should not assume that it has access to the file system IMO (conceptually at least, tsserver is actually very much filesystem-bound).

**Comment by thraizz** [comment]
I see your point, thanks for the fast reply.

Does the server not already assume, even conceptually, that it has file system access by renaming the file? 😸 
Although I can see that creating a directory is a "side effect" that goes beyond the most-basic and therefore expected functionality of a function that renames a file 👍

**Comment by rchl** [comment]
> Does the server not already assume, even conceptually, that it has file system access by renaming the file?

I don't think so since it's designed to ask the editor to handle the rename.

Also as LSP spec states, by triggering `textDocument/didOpen`, the editor assumes ownership of the file so the server is not meant to touch the file then. It would even make editor confused since the un-renamed file would still be open but wouldn't be backed by a physical file. That's why editor needs to do this job.

**Comment by rchl** [comment]
The server supports the [WillRenameFiles Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_willRenameFiles) now and that is the official LSP way of handling file renames.
