### ISSUE TITLE
Typescript lang server forces didOpenTextDocument call before answering LSP requests 

### ISSUE THREAD

**Issue by yuval-piiano** [typescript-language-server/typescript-language-server#636]
in https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didOpen
"  Note that a server’s ability to fulfill requests is independent of whether a text document is open or closed. "
But in the code, documentSymbol for example doesn't work for unopened files . 
JDT ls (Java language server) and pyright (Python's) do work without having to open the files prior to sending documentSymbol,

**Comment by rchl** [comment]
I'm not gonna investigate that (feel free to do that if you have time) but I believe it's a limitation of the `tsserver` (`typescript`) that the file has to be opened before some (or all) features could function properly. You could try quickly hacking the code to ignore didOpen notification and try to request completions for a document (`complete` implementation would have to be changed to not require `documents`).

Another reason `didOpen` is required is because to be able to properly process some `tsserver` responses, we need be able to map them to the document text that we receive through `didOpen`.

**Comment by rchl** [comment]
And I guess what could be done is to read files using Node file system API if it wasn't opened through `textDocument/didOpen` but I really have no plan of doing that as that doesn't seem that useful for use-cases within the editors.

**Comment by rchl** [comment]
The decision here is not to support that use case since it's not relevant for editors.
