### ISSUE TITLE
Call Hierarchy for Emacs LSP-treemacs

### ISSUE THREAD

**Issue by ryan-s-wilson** [typescript-language-server/typescript-language-server#640]
Maybe this is barking up the wrong tree since the call hierarchy is only experimental. Emacs LSP provides call hierarchy functionality through lsp-treemacs. when attempting to use this by `lsp-treemacs-call-hierarchy` it errors saying that `textDocument/prepareCallHierarchy` is an unhandled method.

**Comment by rchl** [comment]
If Emacs LSP uses this server then this is because `textDocument/prepareCallHierarchy` is not implemented. There is only support for older and experimental `textDocument/calls` https://github.com/typescript-language-server/typescript-language-server#callers-and-callees-textdocumentcalls-experimental

So it's a duplicated of #591

**Comment by rchl** [comment]
No idea. What does it say exactly and where?

**Comment by dkasak** [comment]
```
method textDocument/prepareCallHierarchy is not supported by any of the servers registered for the current buffer
```

In the status bar at the bottom when I try to call e.g. `lua vim.lsp.buf.incoming_calls()`. This usually happens when a server in fact does not support the method, so I'm kind of puzzled.

Running `:LspInfo` shows `typescript-language-server` is loaded.

![image](https://user-images.githubusercontent.com/463342/215118295-88ca1f6d-339d-43ac-a5de-155e4f667762.png)

Sanity checking that it's loading the correct version:

```
~ 
❯ which typescript-language-server 
/usr/bin/typescript-language-server

~ 
❯ pacman -Qo /usr/bin/typescript-language-server
/usr/bin/typescript-language-server is owned by typescript-language-server 3.0.3-1

**Comment by rchl** [comment]
Is `typescript` version new enough? Server only reports support when typescript version is 3.8 or above:

```ts
        if (textDocument?.callHierarchy && typescriptVersion.version?.gte(API.v380)) {
            initializeResult.capabilities.callHierarchyProvider = true;
        }
```

**Comment by dkasak** [comment]
Should be new enough. From the LSP client logs:

```
[WARN][2023-01-27 16:27:32] ...lsp/handlers.lua:487	'Using Typescript version (bundled) 4.9.4 from path "/usr/lib/node_modules/typescript/lib/tsserver.js"'
[WARN][2023-01-27 16:33:24] ...lsp/handlers.lua:487	'Using Typescript version (workspace) 4.9.4 from path "/home/dkasak/code/matrix-js-sdk/node_modules/typescript/lib/tsserver.js"'
```

> (Also the client has to announce support for callHierarchy capability)

It works with other LSP servers supporting `callHierarchy`, so I'm assuming it should be doing that.

I'll keep digging.

**Comment by rchl** [comment]
Seeing log of LSP communication since starting the server until it tell you that it's not supported would probably answer all the questions. I don't know how to enable it in your editor)

**Comment by rchl** [comment]
It seems like there was a bug in neovim where it [didn't report client capability properly](https://github.com/neovim/neovim/commit/f7ad46e69ed407579517694ccf3dc1beffe7acdc). Was fixed about 20 days ago so maybe your version doesn't include it yet.

**Comment by dkasak** [comment]
Ah, thanks for the hint, this is it! Looking at the debug logs confirms that the `callHierarchy` capability is announced in the wrong spot.
