### ISSUE TITLE
Is there a way to configure tsserver so that auto-imports will work for module files that aren't in buffer?

### ISSUE THREAD

**Issue by anthony-S93** [typescript-language-server/typescript-language-server#698]
I noticed that auto-imports (on Neovim) only work when I have my module files opened in the buffer. 

For instance, let's say I have the following file `module.js`:
```javascript
function foobar()
{
    console.log("foobar.");
}

function foo()
{
    console.log("foo");
}

export { foobar, foo };
```
Here are two cases where I tried to import the module from another file called `main.js`: 

Case 1: `module.js` isn't open, in which case the auto-import fails.
![failed_autoimport](https://user-images.githubusercontent.com/69449791/222947318-3dca7ab7-d406-4079-83da-ff020f0b133d.gif)

Case 2: `module.js` is open in another buffer alongside `main.js`:
![success_autoimport](https://user-images.githubusercontent.com/69449791/222947365-ea87a93a-5d57-49ed-993b-5c174ec2a2c3.gif)

**Comment by rchl** [comment]
This is expected to work by default. Otherwise it would be pretty useless feature.

Feel free to provide full LSP logs spanning from server start to the point when you reproduce the issue.

Additionally (or alternatively) you can provide a project that reproduces. Then it would be easy to check whether the issue is specific to your setup.

**Comment by anthony-S93** [comment]
You know what? I really ought to punch myself in the face. 

I figured out what the problem was. As it turns out, there was a syntax error inside my `jsconfig.json`... I accidentally deleted a closing brace and left it as it is. 

:man_facepalming:
