### ISSUE TITLE
Debug Failure. Unexpected node.

### ISSUE THREAD

**Issue by directormac** [typescript-language-server/typescript-language-server#896]
```txt
   Error  03:56:49 PM notify.error tsserver: 1: <semantic> TypeScript Server Error (5.4.5)
Debug Failure. Unexpected node.
Node ComputedPropertyName was unexpected.
Error: Debug Failure. Unexpected node.
Node ComputedPropertyName was unexpected.
```

I am using lazyvim as my base, The error only occurs when using bun workspace as the node_modules are hoisted in the workspace root it errors looking for the type hints, When using on a regular ts projects this wont occur only in Bun workspace

**Comment by predragnikolic** [comment]
I think this issue is more suited in the bun repo.

**Comment by directormac** [comment]
> I think this issue is more suited in the bun repo.

Well inlay hints works on vscode but not in neovim tho. maybe its the nvim-lspconfig and tsserver always expecting the node_modules directory to exist in the repo dir.

**Comment by predragnikolic** [comment]
Vs code doesn't use this typescript-language-server.

I'm not sure why you mention inlay hints and how that is related to the above issue. Can you please explain.

You would need to provide steps on how someone can reproduce the same issue, and what the expected and actual behaviors are.

**Comment by 80avin** [comment]
I second this.
I have been seeing this very frequently and it goes away when I disable inlayHints. I am also using LazyVim but the project is in Node.JS and not Bun.

**Comment by rchl** [comment]
First of all, when reporting issues, please provide the code (project) that reproduces the issue. Otherwise no one can help you.

Two, I've seen it happening before. Typically Typescript throws such errors when typing, when the code is momentarily invalid (which is normal when typing). It's not something that can be fixed here. At best we could silence those errors.

Ideally this should be reported in Typescript repo.
And note that it should also happen in VSCode as long as it's using the same Typescript version for type checking (by default it uses built-in Typescript version while you might be using project version).
