### ISSUE TITLE
Unable to initialize, language server cannot read properties of undefined (reading 'workspace')

### ISSUE THREAD

**Issue by chenzhf2019** [typescript-language-server/typescript-language-server#900]
This is my initialize request, I don't know why it can't run, please help me
![image](https://github.com/typescript-language-server/typescript-language-server/assets/59008746/f0ea1228-34a9-4a04-92e5-9f3e0e7c037e)
![image](https://github.com/typescript-language-server/typescript-language-server/assets/59008746/7e7ef5db-8f1f-4a40-8534-3d58216a4134)

`{\n     "jsonrpc": "2.0",\n     "id": 0,\n     "method": "initialize",\n     "params": {\n         "processId": 28292,\n         "clientInfo": {\n             "name": "CodeAnalysisTools",\n             "version": "2.0"\n         },\n         "rootUri": "file:///C%3A/Users/czf/Desktop/workspace/demo",\n         "rootPath": "file:///C%3A/Users/czf/Desktop/workspace/demo",\n         "workspaceFolders":{\n               "uri": "file:///C%3A/Users/czf/Desktop/workspace/demo",\n               "name": "czf"\n         },\n         "trace": "on"\n     }\n }`

**Comment by rchl** [comment]
If you want to use the server manually instead of using it from within an editor that already implements an LSP support then you need to read and follow the [LSP specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialize). In this case you are missing the `capabilities` object, for example.
